    <div style="float:left;position:relative;top:0px;left:0px;text-align:center;width:100%;height:200px;background-color:black;border-top:1px solid black;color:white">
      <br>
    <a href="termsofservice.aspx" style="color:white">TERMS OF SERVICE</a> |
    <a href="newarrivals.aspx" style="color:white">NEW ARRIVALS</a> |
    <a href="contactus.aspx" style="color:white">CONTACT US</a>
    <br>
    Copyright &copy; 2019 AmpleWears, Inc. All Rights Reserved
      </div>
  </body>
</html>