--
-- Create Schema Script
--   Database Version            : 11.2.0.2.0
--   Database Compatible Level   : 11.2.0.0.0
--   Script Compatible Level     : 11.2.0.0.0
--   Toad Version                : 13.1.0.78
--   DB Connect String           : LOCALHOST:1521/XE
--   Schema                      : SA
--   Script Created by           : SA
--   Script Created at           : 3/18/2019 1:44:15 AM
--   Notes                       : 
--

-- Object Counts: 
--   Roles: 3           System Privileges: 211  Roles: 12           Grants: 290 
--   Users: 1           System Privileges: 200  Roles: 3                 
--   Tablespaces: 2     Datafiles: 1        Tempfiles: 1 
-- 
--   Directories: 4 
--   Indexes: 1         Columns: 1          
--   Object Privileges: 2 
--   Sequences: 9 
--   Tables: 16         Columns: 113        Constraints: 1      
--   Triggers: 7 


-- "Set define off" turns off substitution variables.
Set define off; 

--
-- DATA_PUMP_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
DATA_PUMP_DIR AS 
'C:\oraclexe\app\oracle\admin\xe\dpdump\';


--
-- ORACLECLRDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLECLRDIR AS 
'C:\oraclexe\app\oracle\product\11.2.0\server\bin\clr';


--
-- ORACLE_OCM_CONFIG_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLE_OCM_CONFIG_DIR AS 
'C:/ADE/jaikrish_xe/oracle\ccr\state';


--
-- XMLDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XMLDIR AS 
'C:\oraclexe\app\oracle\product\11.2.0\server\rdbms\xml';


--
-- SYSTEM  (Tablespace) 
--
CREATE TABLESPACE SYSTEM DATAFILE 
  'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\SYSTEM.DBF' SIZE 360M AUTOEXTEND ON NEXT 10M MAXSIZE 600M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
FLASHBACK ON;


--
-- TEMP  (Tablespace) 
--
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\TEMP.DBF' SIZE 20M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


--
-- "DEFAULT"  (Profile) 
--
CREATE PROFILE "DEFAULT" LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 10
  PASSWORD_LIFE_TIME 180
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME 7
  PASSWORD_VERIFY_FUNCTION NULL;


--
-- CONNECT  (Role) 
--
CREATE ROLE CONNECT NOT IDENTIFIED;

-- System privileges granted to CONNECT
GRANT CREATE SESSION TO CONNECT;


--
-- DBA  (Role) 
--
CREATE ROLE DBA NOT IDENTIFIED;

-- Object privileges granted to DBA
GRANT EXECUTE ON SYS.AS_REPLAY TO DBA;
GRANT DEBUG ON SYS.AW$ TO DBA;
GRANT SELECT ON SYS.AW$ TO DBA;
GRANT ALTER ON SYS.AWSEQ$ TO DBA;
GRANT SELECT ON SYS.AWSEQ$ TO DBA;
GRANT DEBUG ON SYS.AW_OBJ$ TO DBA;
GRANT SELECT ON SYS.AW_OBJ$ TO DBA;
GRANT DEBUG ON SYS.AW_PROP$ TO DBA;
GRANT SELECT ON SYS.AW_PROP$ TO DBA;
GRANT DEBUG ON SYS.AW_TRACK$ TO DBA;
GRANT SELECT ON SYS.AW_TRACK$ TO DBA;
GRANT EXECUTE ON SYS.DBMS_ADR TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_IMMEDIATE TO DBA;
GRANT EXECUTE ON SYS.DBMS_CACHEUTIL TO DBA;
GRANT EXECUTE ON SYS.DBMS_DEFER_QUERY TO DBA;
GRANT EXECUTE ON SYS.DBMS_DEFER_SYS TO DBA;
GRANT EXECUTE ON SYS.DBMS_DNFS TO DBA;
GRANT EXECUTE ON SYS.DBMS_FEATURE_USAGE_REPORT TO DBA;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO DBA;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK_ARCHIVE TO DBA;
GRANT EXECUTE ON SYS.DBMS_HM TO DBA;
GRANT EXECUTE ON SYS.DBMS_IR TO DBA;
GRANT EXECUTE ON SYS.DBMS_LOGSTDBY TO DBA;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO DBA;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO DBA;
GRANT EXECUTE ON SYS.DBMS_RESUMABLE TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVER_TRACE TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE TO DBA;
GRANT EXECUTE ON SYS.DBMS_STORAGE_MAP TO DBA;
GRANT EXECUTE ON SYS.DBMS_TDB TO DBA;
GRANT EXECUTE ON SYS.DBMS_UADV_ARR TO DBA;
GRANT EXECUTE ON SYS.DBMS_UNDO_ADV TO DBA;
GRANT EXECUTE ON SYS.DBMS_WLM TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_CAPTURE TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPLAY TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO DBA;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS TO DBA;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS_INT TO DBA;
GRANT EXECUTE ON SYS.HM_SQLTK_INTERNAL TO DBA;
GRANT EXECUTE ON SYS.LOAD_UNDO_STAT TO DBA;
GRANT ALTER ON SYS.MAP_OBJECT TO DBA;
GRANT DEBUG ON SYS.MAP_OBJECT TO DBA;
GRANT DELETE ON SYS.MAP_OBJECT TO DBA;
GRANT FLASHBACK ON SYS.MAP_OBJECT TO DBA;
GRANT INSERT ON SYS.MAP_OBJECT TO DBA;
GRANT ON COMMIT REFRESH ON SYS.MAP_OBJECT TO DBA;
GRANT QUERY REWRITE ON SYS.MAP_OBJECT TO DBA;
GRANT SELECT ON SYS.MAP_OBJECT TO DBA;
GRANT UPDATE ON SYS.MAP_OBJECT TO DBA;
GRANT DEBUG ON SYS.OLAP_TAB$ TO DBA;
GRANT SELECT ON SYS.OLAP_TAB$ TO DBA;
GRANT DEBUG ON SYS.OLAP_TAB_COL$ TO DBA;
GRANT SELECT ON SYS.OLAP_TAB_COL$ TO DBA;
GRANT DEBUG ON SYS.OLAP_TAB_HIER$ TO DBA;
GRANT SELECT ON SYS.OLAP_TAB_HIER$ TO DBA;
GRANT EXECUTE ON SYS.OUTLN_EDIT_PKG TO DBA;
GRANT EXECUTE ON SYS.OUTLN_PKG TO DBA;
GRANT DEBUG ON SYS.PS$ TO DBA;
GRANT SELECT ON SYS.PS$ TO DBA;
GRANT EXECUTE ON SYS.RESET_UNDO_STAT TO DBA;
GRANT SELECT ON SYS.V$XS_SESSION TO DBA;
GRANT SELECT ON SYS.V$XS_SESSION_ATTRIBUTE TO DBA;
GRANT SELECT ON SYS.V$XS_SESSION_ROLE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_INVALIDATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_AMS_XACTION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_ACT_MAP TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_TYPE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_CAPTURE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DIAGV_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DIR_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_DIAG_JOB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_TARGET_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_USER_ACTIVITY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_FDG_SET TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_FINDING TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_MESSAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_RECOMMENDATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_RUN TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCCKEY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_CONFIG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_IMPT_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_PK_IMPTS TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_SUMMARY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_CONFIGURATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_COPY_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_METADATA TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_HISTORY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PKG_UNPACK_HIST TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PROGRESS_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_REMOTE_PACKAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PICKLEERR TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_RELMD_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_SWEEPERR TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VHM_RUN TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIEW TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIEWCOL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINC_METER_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_COPY_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_METADATA TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_HISTORY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_MAIN_INT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_SIZE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_CAND TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_MAIN_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VNOT_EXIST_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM2 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET_COUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_INT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_LASTINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWCATVIEW TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB_I TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VTEST_EXISTS TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_ACTINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_ACTPROB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INCCOUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INCFCOUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INC_METER_INFO_PROB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_NFCINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_SWPERRCOUNT TO DBA;
GRANT EXECUTE ON XDB.DBMS_CSX_ADMIN TO DBA;
GRANT EXECUTE ON XDB.DBMS_XDB_ADMIN TO DBA;
GRANT ALTER ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT DEBUG ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT DELETE ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT FLASHBACK ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT INSERT ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT ON COMMIT REFRESH ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT QUERY REWRITE ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT SELECT ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT UPDATE ON XDB.X$PT6NE764J1LJ8VNON8UGHPU1T088 TO DBA;
GRANT ALTER ON XDB.XDB$ACL TO DBA;
GRANT DEBUG ON XDB.XDB$ACL TO DBA;
GRANT DELETE ON XDB.XDB$ACL TO DBA;
GRANT FLASHBACK ON XDB.XDB$ACL TO DBA;
GRANT INSERT ON XDB.XDB$ACL TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$ACL TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$ACL TO DBA;
GRANT SELECT ON XDB.XDB$ACL TO DBA;
GRANT UPDATE ON XDB.XDB$ACL TO DBA;
GRANT ALTER ON XDB.XDB$CHECKOUTS TO DBA;
GRANT DEBUG ON XDB.XDB$CHECKOUTS TO DBA;
GRANT DELETE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT FLASHBACK ON XDB.XDB$CHECKOUTS TO DBA;
GRANT INSERT ON XDB.XDB$CHECKOUTS TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$CHECKOUTS TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT SELECT ON XDB.XDB$CHECKOUTS TO DBA;
GRANT UPDATE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT ALTER ON XDB.XDB$CONFIG TO DBA;
GRANT DEBUG ON XDB.XDB$CONFIG TO DBA;
GRANT DELETE ON XDB.XDB$CONFIG TO DBA;
GRANT FLASHBACK ON XDB.XDB$CONFIG TO DBA;
GRANT INSERT ON XDB.XDB$CONFIG TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$CONFIG TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$CONFIG TO DBA;
GRANT SELECT ON XDB.XDB$CONFIG TO DBA;
GRANT UPDATE ON XDB.XDB$CONFIG TO DBA;
GRANT ALTER ON XDB.XDB$D_LINK TO DBA;
GRANT DEBUG ON XDB.XDB$D_LINK TO DBA;
GRANT DELETE ON XDB.XDB$D_LINK TO DBA;
GRANT FLASHBACK ON XDB.XDB$D_LINK TO DBA;
GRANT INSERT ON XDB.XDB$D_LINK TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$D_LINK TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$D_LINK TO DBA;
GRANT SELECT ON XDB.XDB$D_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$D_LINK TO DBA;
GRANT ALTER ON XDB.XDB$H_INDEX TO DBA;
GRANT DEBUG ON XDB.XDB$H_INDEX TO DBA;
GRANT DELETE ON XDB.XDB$H_INDEX TO DBA;
GRANT FLASHBACK ON XDB.XDB$H_INDEX TO DBA;
GRANT INSERT ON XDB.XDB$H_INDEX TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$H_INDEX TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$H_INDEX TO DBA;
GRANT SELECT ON XDB.XDB$H_INDEX TO DBA;
GRANT UPDATE ON XDB.XDB$H_INDEX TO DBA;
GRANT ALTER ON XDB.XDB$H_LINK TO DBA;
GRANT DEBUG ON XDB.XDB$H_LINK TO DBA;
GRANT DELETE ON XDB.XDB$H_LINK TO DBA;
GRANT FLASHBACK ON XDB.XDB$H_LINK TO DBA;
GRANT INSERT ON XDB.XDB$H_LINK TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$H_LINK TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$H_LINK TO DBA;
GRANT SELECT ON XDB.XDB$H_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$H_LINK TO DBA;
GRANT ALTER ON XDB.XDB$NLOCKS TO DBA;
GRANT DEBUG ON XDB.XDB$NLOCKS TO DBA;
GRANT DELETE ON XDB.XDB$NLOCKS TO DBA;
GRANT FLASHBACK ON XDB.XDB$NLOCKS TO DBA;
GRANT INSERT ON XDB.XDB$NLOCKS TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$NLOCKS TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$NLOCKS TO DBA;
GRANT SELECT ON XDB.XDB$NLOCKS TO DBA;
GRANT UPDATE ON XDB.XDB$NLOCKS TO DBA;
GRANT ALTER ON XDB.XDB$RESCONFIG TO DBA;
GRANT DEBUG ON XDB.XDB$RESCONFIG TO DBA;
GRANT DELETE ON XDB.XDB$RESCONFIG TO DBA;
GRANT FLASHBACK ON XDB.XDB$RESCONFIG TO DBA;
GRANT INSERT ON XDB.XDB$RESCONFIG TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$RESCONFIG TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$RESCONFIG TO DBA;
GRANT SELECT ON XDB.XDB$RESCONFIG TO DBA;
GRANT UPDATE ON XDB.XDB$RESCONFIG TO DBA;
GRANT ALTER ON XDB.XDB$RESOURCE TO DBA;
GRANT DEBUG ON XDB.XDB$RESOURCE TO DBA;
GRANT DELETE ON XDB.XDB$RESOURCE TO DBA;
GRANT FLASHBACK ON XDB.XDB$RESOURCE TO DBA;
GRANT INSERT ON XDB.XDB$RESOURCE TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$RESOURCE TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$RESOURCE TO DBA;
GRANT SELECT ON XDB.XDB$RESOURCE TO DBA;
GRANT UPDATE ON XDB.XDB$RESOURCE TO DBA;
GRANT ALTER ON XDB.XDB$WORKSPACE TO DBA;
GRANT DEBUG ON XDB.XDB$WORKSPACE TO DBA;
GRANT DELETE ON XDB.XDB$WORKSPACE TO DBA;
GRANT FLASHBACK ON XDB.XDB$WORKSPACE TO DBA;
GRANT INSERT ON XDB.XDB$WORKSPACE TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XDB$WORKSPACE TO DBA;
GRANT QUERY REWRITE ON XDB.XDB$WORKSPACE TO DBA;
GRANT SELECT ON XDB.XDB$WORKSPACE TO DBA;
GRANT UPDATE ON XDB.XDB$WORKSPACE TO DBA;
GRANT ALTER ON XDB.XS$DATA_SECURITY TO DBA;
GRANT DEBUG ON XDB.XS$DATA_SECURITY TO DBA;
GRANT DELETE ON XDB.XS$DATA_SECURITY TO DBA;
GRANT FLASHBACK ON XDB.XS$DATA_SECURITY TO DBA;
GRANT INSERT ON XDB.XS$DATA_SECURITY TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XS$DATA_SECURITY TO DBA;
GRANT QUERY REWRITE ON XDB.XS$DATA_SECURITY TO DBA;
GRANT SELECT ON XDB.XS$DATA_SECURITY TO DBA;
GRANT UPDATE ON XDB.XS$DATA_SECURITY TO DBA;
GRANT ALTER ON XDB.XS$PRINCIPALS TO DBA;
GRANT DEBUG ON XDB.XS$PRINCIPALS TO DBA;
GRANT DELETE ON XDB.XS$PRINCIPALS TO DBA;
GRANT FLASHBACK ON XDB.XS$PRINCIPALS TO DBA;
GRANT INSERT ON XDB.XS$PRINCIPALS TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XS$PRINCIPALS TO DBA;
GRANT QUERY REWRITE ON XDB.XS$PRINCIPALS TO DBA;
GRANT SELECT ON XDB.XS$PRINCIPALS TO DBA;
GRANT UPDATE ON XDB.XS$PRINCIPALS TO DBA;
GRANT ALTER ON XDB.XS$ROLESETS TO DBA;
GRANT DEBUG ON XDB.XS$ROLESETS TO DBA;
GRANT DELETE ON XDB.XS$ROLESETS TO DBA;
GRANT FLASHBACK ON XDB.XS$ROLESETS TO DBA;
GRANT INSERT ON XDB.XS$ROLESETS TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XS$ROLESETS TO DBA;
GRANT QUERY REWRITE ON XDB.XS$ROLESETS TO DBA;
GRANT SELECT ON XDB.XS$ROLESETS TO DBA;
GRANT UPDATE ON XDB.XS$ROLESETS TO DBA;
GRANT ALTER ON XDB.XS$SECURITYCLASS TO DBA;
GRANT DEBUG ON XDB.XS$SECURITYCLASS TO DBA;
GRANT DELETE ON XDB.XS$SECURITYCLASS TO DBA;
GRANT FLASHBACK ON XDB.XS$SECURITYCLASS TO DBA;
GRANT INSERT ON XDB.XS$SECURITYCLASS TO DBA;
GRANT ON COMMIT REFRESH ON XDB.XS$SECURITYCLASS TO DBA;
GRANT QUERY REWRITE ON XDB.XS$SECURITYCLASS TO DBA;
GRANT SELECT ON XDB.XS$SECURITYCLASS TO DBA;
GRANT UPDATE ON XDB.XS$SECURITYCLASS TO DBA;

-- System privileges granted to DBA
GRANT ADMINISTER ANY SQL TUNING SET TO DBA WITH ADMIN OPTION;
GRANT ADMINISTER DATABASE TRIGGER TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'DBA', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => TRUE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO DBA WITH ADMIN OPTION;
GRANT ADMINISTER SQL TUNING SET TO DBA WITH ADMIN OPTION;
GRANT ADVISOR TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY ASSEMBLY TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY CLUSTER TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY CUBE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY DIMENSION TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY EDITION TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT ALTER ANY INDEX TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY INDEXTYPE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY LIBRARY TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY MATERIALIZED VIEW TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY MINING MODEL TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY OPERATOR TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY OUTLINE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT ALTER ANY SEQUENCE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY SQL PROFILE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO DBA WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO DBA WITH ADMIN OPTION;
GRANT ALTER DATABASE TO DBA WITH ADMIN OPTION;
GRANT ALTER PROFILE TO DBA WITH ADMIN OPTION;
GRANT ALTER RESOURCE COST TO DBA WITH ADMIN OPTION;
GRANT ALTER ROLLBACK SEGMENT TO DBA WITH ADMIN OPTION;
GRANT ALTER SESSION TO DBA WITH ADMIN OPTION;
GRANT ALTER SYSTEM TO DBA WITH ADMIN OPTION;
GRANT ALTER TABLESPACE TO DBA WITH ADMIN OPTION;
GRANT ALTER USER TO DBA WITH ADMIN OPTION;
GRANT ANALYZE ANY TO DBA WITH ADMIN OPTION;
GRANT ANALYZE ANY DICTIONARY TO DBA WITH ADMIN OPTION;
GRANT AUDIT ANY TO DBA WITH ADMIN OPTION;
GRANT AUDIT SYSTEM TO DBA WITH ADMIN OPTION;
GRANT BACKUP ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT BECOME USER TO DBA WITH ADMIN OPTION;
GRANT CHANGE NOTIFICATION TO DBA WITH ADMIN OPTION;
GRANT COMMENT ANY MINING MODEL TO DBA WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY ASSEMBLY TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY CLUSTER TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY CUBE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY CUBE BUILD PROCESS TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY DIMENSION TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY DIRECTORY TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY EDITION TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT CREATE ANY INDEX TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY INDEXTYPE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY JOB TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY LIBRARY TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY MEASURE FOLDER TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY MINING MODEL TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY OPERATOR TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY OUTLINE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT CREATE ANY SEQUENCE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY SQL PROFILE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY TYPE TO DBA WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO DBA WITH ADMIN OPTION;
GRANT CREATE ASSEMBLY TO DBA WITH ADMIN OPTION;
GRANT CREATE CLUSTER TO DBA WITH ADMIN OPTION;
GRANT CREATE CUBE TO DBA WITH ADMIN OPTION;
GRANT CREATE CUBE BUILD PROCESS TO DBA WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO DBA WITH ADMIN OPTION;
GRANT CREATE DIMENSION TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT CREATE EXTERNAL JOB TO DBA WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO DBA WITH ADMIN OPTION;
GRANT CREATE JOB TO DBA WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO DBA WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO DBA WITH ADMIN OPTION;
GRANT CREATE MEASURE FOLDER TO DBA WITH ADMIN OPTION;
GRANT CREATE MINING MODEL TO DBA WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO DBA WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO DBA WITH ADMIN OPTION;
GRANT CREATE PROFILE TO DBA WITH ADMIN OPTION;
GRANT CREATE PUBLIC DATABASE LINK TO DBA WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO DBA WITH ADMIN OPTION;
GRANT CREATE ROLE TO DBA WITH ADMIN OPTION;
GRANT CREATE ROLLBACK SEGMENT TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT CREATE SEQUENCE TO DBA WITH ADMIN OPTION;
GRANT CREATE SESSION TO DBA WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO DBA WITH ADMIN OPTION;
GRANT CREATE TABLE TO DBA WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO DBA WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO DBA WITH ADMIN OPTION;
GRANT CREATE TYPE TO DBA WITH ADMIN OPTION;
GRANT CREATE USER TO DBA WITH ADMIN OPTION;
GRANT CREATE VIEW TO DBA WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO DBA WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO DBA WITH ADMIN OPTION;
GRANT DELETE ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT DELETE ANY MEASURE FOLDER TO DBA WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => TRUE);
END;
/
GRANT DROP ANY ASSEMBLY TO DBA WITH ADMIN OPTION;
GRANT DROP ANY CLUSTER TO DBA WITH ADMIN OPTION;
GRANT DROP ANY CONTEXT TO DBA WITH ADMIN OPTION;
GRANT DROP ANY CUBE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY CUBE BUILD PROCESS TO DBA WITH ADMIN OPTION;
GRANT DROP ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT DROP ANY DIMENSION TO DBA WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO DBA WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT DROP ANY INDEX TO DBA WITH ADMIN OPTION;
GRANT DROP ANY INDEXTYPE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY LIBRARY TO DBA WITH ADMIN OPTION;
GRANT DROP ANY MATERIALIZED VIEW TO DBA WITH ADMIN OPTION;
GRANT DROP ANY MEASURE FOLDER TO DBA WITH ADMIN OPTION;
GRANT DROP ANY MINING MODEL TO DBA WITH ADMIN OPTION;
GRANT DROP ANY OPERATOR TO DBA WITH ADMIN OPTION;
GRANT DROP ANY OUTLINE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT DROP ANY SEQUENCE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY SQL PROFILE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO DBA WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO DBA WITH ADMIN OPTION;
GRANT DROP ANY TYPE TO DBA WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO DBA WITH ADMIN OPTION;
GRANT DROP PROFILE TO DBA WITH ADMIN OPTION;
GRANT DROP PUBLIC DATABASE LINK TO DBA WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO DBA WITH ADMIN OPTION;
GRANT DROP ROLLBACK SEGMENT TO DBA WITH ADMIN OPTION;
GRANT DROP TABLESPACE TO DBA WITH ADMIN OPTION;
GRANT DROP USER TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => TRUE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY CLASS TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY LIBRARY TO DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY OPERATOR TO DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY PROGRAM TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => TRUE);
END;
/
GRANT EXECUTE ANY TYPE TO DBA WITH ADMIN OPTION;
GRANT EXECUTE ASSEMBLY TO DBA WITH ADMIN OPTION;
GRANT EXPORT FULL DATABASE TO DBA WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT FLASHBACK ARCHIVE ADMINISTER TO DBA WITH ADMIN OPTION;
GRANT FORCE ANY TRANSACTION TO DBA WITH ADMIN OPTION;
GRANT FORCE TRANSACTION TO DBA WITH ADMIN OPTION;
GRANT GLOBAL QUERY REWRITE TO DBA WITH ADMIN OPTION;
GRANT GRANT ANY OBJECT PRIVILEGE TO DBA WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO DBA WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO DBA WITH ADMIN OPTION;
GRANT IMPORT FULL DATABASE TO DBA WITH ADMIN OPTION;
GRANT INSERT ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT INSERT ANY MEASURE FOLDER TO DBA WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT LOCK ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT MANAGE ANY FILE GROUP TO DBA WITH ADMIN OPTION;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => TRUE);
END;
/
GRANT MANAGE FILE GROUP TO DBA WITH ADMIN OPTION;
GRANT MANAGE SCHEDULER TO DBA WITH ADMIN OPTION;
GRANT MANAGE TABLESPACE TO DBA WITH ADMIN OPTION;
GRANT MERGE ANY VIEW TO DBA WITH ADMIN OPTION;
GRANT ON COMMIT REFRESH TO DBA WITH ADMIN OPTION;
GRANT QUERY REWRITE TO DBA WITH ADMIN OPTION;
GRANT READ ANY FILE GROUP TO DBA WITH ADMIN OPTION;
GRANT RESTRICTED SESSION TO DBA WITH ADMIN OPTION;
GRANT RESUMABLE TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY CUBE TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY MINING MODEL TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO DBA WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO DBA WITH ADMIN OPTION;
GRANT UNDER ANY TYPE TO DBA WITH ADMIN OPTION;
GRANT UNDER ANY VIEW TO DBA WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO DBA WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE TO DBA WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE BUILD PROCESS TO DBA WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE DIMENSION TO DBA WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO DBA WITH ADMIN OPTION;

-- Roles granted to DBA
--
-- DATAPUMP_EXP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_EXP_FULL_DATABASE TO DBA;
--
-- DATAPUMP_IMP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_IMP_FULL_DATABASE TO DBA;
--
-- DELETE_CATALOG_ROLE  (Role) 
--
GRANT DELETE_CATALOG_ROLE TO DBA WITH ADMIN OPTION;
--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
GRANT EXECUTE_CATALOG_ROLE TO DBA WITH ADMIN OPTION;
--
-- EXP_FULL_DATABASE  (Role) 
--
GRANT EXP_FULL_DATABASE TO DBA;
--
-- GATHER_SYSTEM_STATISTICS  (Role) 
--
GRANT GATHER_SYSTEM_STATISTICS TO DBA;
--
-- IMP_FULL_DATABASE  (Role) 
--
GRANT IMP_FULL_DATABASE TO DBA;
--
-- PLUSTRACE  (Role) 
--
GRANT PLUSTRACE TO DBA WITH ADMIN OPTION;
--
-- SCHEDULER_ADMIN  (Role) 
--
GRANT SCHEDULER_ADMIN TO DBA WITH ADMIN OPTION;
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO DBA WITH ADMIN OPTION;
--
-- XDBADMIN  (Role) 
--
GRANT XDBADMIN TO DBA;
--
-- XDB_SET_INVOKER  (Role) 
--
GRANT XDB_SET_INVOKER TO DBA;


--
-- RESOURCE  (Role) 
--
CREATE ROLE RESOURCE NOT IDENTIFIED;

-- System privileges granted to RESOURCE
GRANT CREATE CLUSTER TO RESOURCE;
GRANT CREATE INDEXTYPE TO RESOURCE;
GRANT CREATE OPERATOR TO RESOURCE;
GRANT CREATE PROCEDURE TO RESOURCE;
GRANT CREATE SEQUENCE TO RESOURCE;
GRANT CREATE TABLE TO RESOURCE;
GRANT CREATE TRIGGER TO RESOURCE;
GRANT CREATE TYPE TO RESOURCE;


--
-- SA  (User) 
--
CREATE USER SA
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 3 Roles for SA 
--
-- CONNECT  (Role) 
--
GRANT CONNECT TO SA;
--
-- DBA  (Role) 
--
GRANT DBA TO SA;
--
-- RESOURCE  (Role) 
--
GRANT RESOURCE TO SA;
ALTER USER SA DEFAULT ROLE ALL;

-- 200 System Privileges for SA 
GRANT ADMINISTER ANY SQL TUNING SET TO SA;
GRANT ADMINISTER DATABASE TRIGGER TO SA;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'SA', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO SA;
GRANT ADMINISTER SQL TUNING SET TO SA;
GRANT ADVISOR TO SA;
GRANT ALTER ANY ASSEMBLY TO SA;
GRANT ALTER ANY CLUSTER TO SA;
GRANT ALTER ANY CUBE TO SA;
GRANT ALTER ANY CUBE DIMENSION TO SA;
GRANT ALTER ANY DIMENSION TO SA;
GRANT ALTER ANY EDITION TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY INDEX TO SA;
GRANT ALTER ANY INDEXTYPE TO SA;
GRANT ALTER ANY LIBRARY TO SA;
GRANT ALTER ANY MATERIALIZED VIEW TO SA;
GRANT ALTER ANY MINING MODEL TO SA;
GRANT ALTER ANY OPERATOR TO SA;
GRANT ALTER ANY OUTLINE TO SA;
GRANT ALTER ANY PROCEDURE TO SA;
GRANT ALTER ANY ROLE TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO SA;
GRANT ALTER ANY SQL PROFILE TO SA;
GRANT ALTER ANY TABLE TO SA;
GRANT ALTER ANY TRIGGER TO SA;
GRANT ALTER ANY TYPE TO SA;
GRANT ALTER DATABASE TO SA;
GRANT ALTER PROFILE TO SA;
GRANT ALTER RESOURCE COST TO SA;
GRANT ALTER ROLLBACK SEGMENT TO SA;
GRANT ALTER SESSION TO SA;
GRANT ALTER SYSTEM TO SA;
GRANT ALTER TABLESPACE TO SA;
GRANT ALTER USER TO SA;
GRANT ANALYZE ANY TO SA;
GRANT AUDIT ANY TO SA;
GRANT AUDIT SYSTEM TO SA;
GRANT BACKUP ANY TABLE TO SA;
GRANT BECOME USER TO SA;
GRANT CHANGE NOTIFICATION TO SA;
GRANT COMMENT ANY MINING MODEL TO SA;
GRANT COMMENT ANY TABLE TO SA;
GRANT CREATE ANY ASSEMBLY TO SA;
GRANT CREATE ANY CLUSTER TO SA;
GRANT CREATE ANY CONTEXT TO SA;
GRANT CREATE ANY CUBE TO SA;
GRANT CREATE ANY CUBE BUILD PROCESS TO SA;
GRANT CREATE ANY CUBE DIMENSION TO SA;
GRANT CREATE ANY DIMENSION TO SA;
GRANT CREATE ANY DIRECTORY TO SA;
GRANT CREATE ANY EDITION TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY INDEX TO SA;
GRANT CREATE ANY INDEXTYPE TO SA;
GRANT CREATE ANY JOB TO SA;
GRANT CREATE ANY LIBRARY TO SA;
GRANT CREATE ANY MATERIALIZED VIEW TO SA;
GRANT CREATE ANY MEASURE FOLDER TO SA;
GRANT CREATE ANY MINING MODEL TO SA;
GRANT CREATE ANY OPERATOR TO SA;
GRANT CREATE ANY OUTLINE TO SA;
GRANT CREATE ANY PROCEDURE TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO SA;
GRANT CREATE ANY SQL PROFILE TO SA;
GRANT CREATE ANY SYNONYM TO SA;
GRANT CREATE ANY TABLE TO SA;
GRANT CREATE ANY TRIGGER TO SA;
GRANT CREATE ANY TYPE TO SA;
GRANT CREATE ANY VIEW TO SA;
GRANT CREATE ASSEMBLY TO SA;
GRANT CREATE CLUSTER TO SA;
GRANT CREATE CUBE TO SA;
GRANT CREATE CUBE BUILD PROCESS TO SA;
GRANT CREATE CUBE DIMENSION TO SA;
GRANT CREATE DATABASE LINK TO SA;
GRANT CREATE DIMENSION TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO SA;
GRANT CREATE INDEXTYPE TO SA;
GRANT CREATE JOB TO SA;
GRANT CREATE LIBRARY TO SA;
GRANT CREATE MATERIALIZED VIEW TO SA;
GRANT CREATE MEASURE FOLDER TO SA;
GRANT CREATE MINING MODEL TO SA;
GRANT CREATE OPERATOR TO SA;
GRANT CREATE PROCEDURE TO SA;
GRANT CREATE PROFILE TO SA;
GRANT CREATE PUBLIC DATABASE LINK TO SA;
GRANT CREATE PUBLIC SYNONYM TO SA;
GRANT CREATE ROLE TO SA;
GRANT CREATE ROLLBACK SEGMENT TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO SA;
GRANT CREATE SESSION TO SA;
GRANT CREATE SYNONYM TO SA;
GRANT CREATE TABLE TO SA;
GRANT CREATE TABLESPACE TO SA;
GRANT CREATE TRIGGER TO SA;
GRANT CREATE TYPE TO SA;
GRANT CREATE USER TO SA;
GRANT CREATE VIEW TO SA;
GRANT DEBUG ANY PROCEDURE TO SA;
GRANT DEBUG CONNECT SESSION TO SA;
GRANT DELETE ANY CUBE DIMENSION TO SA;
GRANT DELETE ANY MEASURE FOLDER TO SA;
GRANT DELETE ANY TABLE TO SA;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'SA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ASSEMBLY TO SA;
GRANT DROP ANY CLUSTER TO SA;
GRANT DROP ANY CONTEXT TO SA;
GRANT DROP ANY CUBE TO SA;
GRANT DROP ANY CUBE BUILD PROCESS TO SA;
GRANT DROP ANY CUBE DIMENSION TO SA;
GRANT DROP ANY DIMENSION TO SA;
GRANT DROP ANY DIRECTORY TO SA;
GRANT DROP ANY EDITION TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY INDEX TO SA;
GRANT DROP ANY INDEXTYPE TO SA;
GRANT DROP ANY LIBRARY TO SA;
GRANT DROP ANY MATERIALIZED VIEW TO SA;
GRANT DROP ANY MEASURE FOLDER TO SA;
GRANT DROP ANY MINING MODEL TO SA;
GRANT DROP ANY OPERATOR TO SA;
GRANT DROP ANY OUTLINE TO SA;
GRANT DROP ANY PROCEDURE TO SA;
GRANT DROP ANY ROLE TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO SA;
GRANT DROP ANY SQL PROFILE TO SA;
GRANT DROP ANY SYNONYM TO SA;
GRANT DROP ANY TABLE TO SA;
GRANT DROP ANY TRIGGER TO SA;
GRANT DROP ANY TYPE TO SA;
GRANT DROP ANY VIEW TO SA;
GRANT DROP PROFILE TO SA;
GRANT DROP PUBLIC DATABASE LINK TO SA;
GRANT DROP PUBLIC SYNONYM TO SA;
GRANT DROP ROLLBACK SEGMENT TO SA;
GRANT DROP TABLESPACE TO SA;
GRANT DROP USER TO SA;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'SA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO SA;
GRANT EXECUTE ANY CLASS TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO SA;
GRANT EXECUTE ANY LIBRARY TO SA;
GRANT EXECUTE ANY OPERATOR TO SA;
GRANT EXECUTE ANY PROCEDURE TO SA;
GRANT EXECUTE ANY PROGRAM TO SA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'SA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO SA;
GRANT EXECUTE ASSEMBLY TO SA;
GRANT EXPORT FULL DATABASE TO SA;
GRANT FLASHBACK ANY TABLE TO SA;
GRANT FLASHBACK ARCHIVE ADMINISTER TO SA;
GRANT FORCE ANY TRANSACTION TO SA;
GRANT FORCE TRANSACTION TO SA;
GRANT GLOBAL QUERY REWRITE TO SA;
GRANT GRANT ANY OBJECT PRIVILEGE TO SA;
GRANT GRANT ANY PRIVILEGE TO SA;
GRANT GRANT ANY ROLE TO SA;
GRANT IMPORT FULL DATABASE TO SA;
GRANT INSERT ANY CUBE DIMENSION TO SA;
GRANT INSERT ANY MEASURE FOLDER TO SA;
GRANT INSERT ANY TABLE TO SA;
GRANT LOCK ANY TABLE TO SA;
GRANT MANAGE ANY FILE GROUP TO SA;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'SA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO SA;
GRANT MANAGE SCHEDULER TO SA;
GRANT MANAGE TABLESPACE TO SA;
GRANT MERGE ANY VIEW TO SA;
GRANT ON COMMIT REFRESH TO SA;
GRANT QUERY REWRITE TO SA;
GRANT READ ANY FILE GROUP TO SA;
GRANT RESTRICTED SESSION TO SA;
GRANT RESUMABLE TO SA;
GRANT SELECT ANY CUBE TO SA;
GRANT SELECT ANY CUBE DIMENSION TO SA;
GRANT SELECT ANY MINING MODEL TO SA;
GRANT SELECT ANY SEQUENCE TO SA;
GRANT SELECT ANY TABLE TO SA;
GRANT SELECT ANY TRANSACTION TO SA;
GRANT UNDER ANY TABLE TO SA;
GRANT UNDER ANY TYPE TO SA;
GRANT UNDER ANY VIEW TO SA;
GRANT UNLIMITED TABLESPACE TO SA;
GRANT UPDATE ANY CUBE TO SA;
GRANT UPDATE ANY CUBE BUILD PROCESS TO SA;
GRANT UPDATE ANY CUBE DIMENSION TO SA;
GRANT UPDATE ANY TABLE TO SA;


--
-- ORDER2_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.ORDER2_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- ORDER_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.ORDER_SEQ
  START WITH 122
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- PROD2_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.PROD2_SEQ
  START WITH 61
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- PRODS_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.PRODS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- PROD_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.PROD_SEQ
  START WITH 561
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- SHOPP2_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.SHOPP2_SEQ
  START WITH 41
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- SHOPPERS_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.SHOPPERS_SEQ
  START WITH 21
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- SHOPP_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.SHOPP_SEQ
  START WITH 2
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- SHOP_SEQ  (Sequence) 
--
CREATE SEQUENCE SA.SHOP_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- CART  (Table) 
--
--   Row Count: 41
CREATE TABLE SA.CART
(
  CID     INTEGER,
  ITEMID  INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- CART2  (Table) 
--
--   Row Count: 33
CREATE TABLE SA.CART2
(
  CID     INTEGER,
  ITEMID  INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- ORDERITEMS  (Table) 
--
--   Row Count: 11
CREATE TABLE SA.ORDERITEMS
(
  ORDERID  INTEGER,
  ITEMID   INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- ORDERITEMS2  (Table) 
--
--   Row Count: 5
CREATE TABLE SA.ORDERITEMS2
(
  ORDERID  INTEGER,
  ITEMID   INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- PRODUCTS  (Table) 
--
--   Row Count: 77
CREATE TABLE SA.PRODUCTS
(
  CATEGORY        VARCHAR2(50 BYTE),
  NAME            VARCHAR2(150 BYTE),
  PRICE           NUMBER(18,2),
  DSC             VARCHAR2(2000 BYTE),
  ITEMID          INTEGER,
  DISCOUNT        INTEGER,
  BESTSELLER      INTEGER,
  RECOMMENDATION  INTEGER,
  IMAGE           VARCHAR2(250 BYTE),
  WEIGHT          NUMBER(18,2),
  NEWARRIVALS     INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- PRODUCTS2  (Table) 
--
--   Row Count: 28
CREATE TABLE SA.PRODUCTS2
(
  CATEGORY        VARCHAR2(50 BYTE),
  NAME            VARCHAR2(150 BYTE),
  PRICE           NUMBER(18,2),
  DSC             VARCHAR2(2000 BYTE),
  ITEMID          INTEGER,
  DISCOUNT        INTEGER,
  BESTSELLER      INTEGER,
  RECOMMENDATION  INTEGER,
  IMAGE           VARCHAR2(250 BYTE),
  WEIGHT          NUMBER(18,2),
  NEWARRIVALS     INTEGER,
  WOMEN           NUMBER,
  MEN             NUMBER,
  FEATURED        INTEGER,
  CATEGORY2       VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- SHOPPERS  (Table) 
--
--   Row Count: 1
CREATE TABLE SA.SHOPPERS
(
  FIRSTNAME        VARCHAR2(50 BYTE),
  LASTNAME         VARCHAR2(50 BYTE),
  USERNAME         VARCHAR2(50 BYTE),
  PASSWORD         VARCHAR2(500 BYTE),
  ADDRESS          VARCHAR2(500 BYTE),
  CITY             VARCHAR2(100 BYTE),
  STATEORPROVINCE  VARCHAR2(200 BYTE),
  COUNTRY          VARCHAR2(100 BYTE),
  PHONE            VARCHAR2(50 BYTE),
  FAX              VARCHAR2(50 BYTE),
  EMAIL            VARCHAR2(250 BYTE),
  PAYPAL_USER      VARCHAR2(250 BYTE),
  SUBSCRIBE        INTEGER,
  USERID           INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- SHOPPERS2  (Table) 
--
--   Row Count: 2
CREATE TABLE SA.SHOPPERS2
(
  FIRSTNAME        VARCHAR2(50 BYTE),
  LASTNAME         VARCHAR2(50 BYTE),
  USERNAME         VARCHAR2(50 BYTE),
  PASSWORD         VARCHAR2(500 BYTE),
  ADDRESS          VARCHAR2(500 BYTE),
  CITY             VARCHAR2(100 BYTE),
  STATEORPROVINCE  VARCHAR2(200 BYTE),
  COUNTRY          VARCHAR2(100 BYTE),
  PHONE            VARCHAR2(50 BYTE),
  FAX              VARCHAR2(50 BYTE),
  EMAIL            VARCHAR2(250 BYTE),
  PAYPAL_USER      VARCHAR2(250 BYTE),
  SUBSCRIBE        INTEGER,
  USERID           INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- SUBSCRIPTION  (Table) 
--
--   Row Count: 4
CREATE TABLE SA.SUBSCRIPTION
(
  EMAIL  VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "cart"  (Table) 
--
--   Row Count: 266
CREATE TABLE SA."cart"
(
  CID     INTEGER,
  ITEMID  INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "cart2"  (Table) 
--
--   Row Count: 0
CREATE TABLE SA."cart2"
(
  CID     INTEGER,
  ITEMID  INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "order"  (Table) 
--
--   Row Count: 41
CREATE TABLE SA."order"
(
  ORDERID         INTEGER,
  USERNAME        VARCHAR2(500 BYTE),
  S_ADDRESS       VARCHAR2(500 BYTE),
  S_CITY          VARCHAR2(500 BYTE),
  S_STATE         VARCHAR2(500 BYTE),
  S_ZIPCODE       VARCHAR2(500 BYTE),
  S_COUNTRY       VARCHAR2(500 BYTE),
  SHIPPINGMETHOD  VARCHAR2(250 BYTE),
  SHIPPINGCOST    NUMBER(18,2),
  PRICE           NUMBER(18,2),
  INPUTDATE       DATE,
  STATUS          VARCHAR2(100 BYTE),
  TRANSID         VARCHAR2(100 BYTE),
  CC4             VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "order2"  (Table) 
--
--   Row Count: 4
CREATE TABLE SA."order2"
(
  ORDERID         INTEGER,
  USERNAME        VARCHAR2(500 BYTE),
  S_ADDRESS       VARCHAR2(500 BYTE),
  S_CITY          VARCHAR2(500 BYTE),
  S_STATE         VARCHAR2(500 BYTE),
  S_ZIPCODE       VARCHAR2(500 BYTE),
  S_COUNTRY       VARCHAR2(500 BYTE),
  SHIPPINGMETHOD  VARCHAR2(250 BYTE),
  SHIPPINGCOST    NUMBER(18,2),
  PRICE           NUMBER(18,2),
  INPUTDATE       TIMESTAMP(6),
  CC4             VARCHAR2(100 BYTE),
  TRANSID         VARCHAR2(100 BYTE),
  STATUS          VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "orderitems"  (Table) 
--
--   Row Count: 35
CREATE TABLE SA."orderitems"
(
  ORDERID  INTEGER,
  ITEMID   INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "orderitems2"  (Table) 
--
--   Row Count: 0
CREATE TABLE SA."orderitems2"
(
  ORDERID  INTEGER,
  ITEMID   INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- "shoppers"  (Table) 
--
--   Row Count: 19
CREATE TABLE SA."shoppers"
(
  FIRSTNAME        VARCHAR2(50 BYTE),
  LASTNAME         VARCHAR2(50 BYTE),
  USERNAME         VARCHAR2(50 BYTE),
  PASSWORD         VARCHAR2(50 BYTE),
  ADDRESS          VARCHAR2(500 BYTE),
  CITY             VARCHAR2(100 BYTE),
  STATEORPROVINCE  VARCHAR2(200 BYTE),
  COUNTRY          VARCHAR2(100 BYTE),
  PHONE            VARCHAR2(50 BYTE),
  FAX              VARCHAR2(50 BYTE),
  EMAIL            VARCHAR2(250 BYTE),
  PAYPAL_USER      VARCHAR2(250 BYTE),
  SUBSCRIBE        INTEGER,
  USERID           INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- EMAIL_PK  (Index) 
--
--  Dependencies: 
--   SUBSCRIPTION (Table)
--
CREATE UNIQUE INDEX SA.EMAIL_PK ON SA.SUBSCRIPTION
(EMAIL)
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--
-- ORDERS2_BI  (Trigger) 
--
--  Dependencies: 
--   "order2" (Table)
--   DUAL (Synonym)
--   ORDER_SEQ (Sequence)
--   STANDARD (Package)
--
CREATE OR REPLACE TRIGGER SA.orders2_bi
BEFORE INSERT ON SA."order2"
FOR EACH ROW
BEGIN
  SELECT order_seq.nextval
  INTO :new.orderid
  FROM dual;
END;
/


--
-- ORDERS_BI  (Trigger) 
--
--  Dependencies: 
--   "order" (Table)
--   ORDER_SEQ (Sequence)
--   DUAL (Synonym)
--   STANDARD (Package)
--
CREATE OR REPLACE TRIGGER SA.orders_bi
BEFORE INSERT ON SA."order"
FOR EACH ROW
BEGIN
  SELECT order_seq.nextval
  INTO :new.orderid
  FROM dual;
END;
/


--
-- PROD2_BI  (Trigger) 
--
--  Dependencies: 
--   PRODUCTS2 (Table)
--   DUAL (Synonym)
--   STANDARD (Package)
--   PROD2_SEQ (Sequence)
--
CREATE OR REPLACE TRIGGER SA.prod2_bi
BEFORE INSERT ON SA.PRODUCTS2
FOR EACH ROW
BEGIN
  SELECT prod2_seq.nextval
  INTO :new.itemid
  FROM dual;
END;
/


--
-- PRODS_BI  (Trigger) 
--
--  Dependencies: 
--   PRODUCTS (Table)
--   PROD_SEQ (Sequence)
--   STANDARD (Package)
--   DUAL (Synonym)
--
CREATE OR REPLACE TRIGGER SA.prods_bi
BEFORE INSERT ON SA.PRODUCTS
FOR EACH ROW
BEGIN
  SELECT prod_seq.nextval
  INTO :new.itemid
  FROM dual;
END;
/


--
-- SHOPP2_BI  (Trigger) 
--
--  Dependencies: 
--   SHOPPERS2 (Table)
--   SHOPP2_SEQ (Sequence)
--   STANDARD (Package)
--   DUAL (Synonym)
--
CREATE OR REPLACE TRIGGER SA.shopp2_bi
BEFORE INSERT ON SA.SHOPPERS2
FOR EACH ROW
BEGIN
  SELECT shopp2_seq.nextval
  INTO :new.userid
  FROM dual;
END;
/


--
-- SHOPPERS_BI  (Trigger) 
--
--  Dependencies: 
--   "shoppers" (Table)
--   STANDARD (Package)
--   SHOPPERS_SEQ (Sequence)
--   DUAL (Synonym)
--
CREATE OR REPLACE TRIGGER SA.shoppers_bi
BEFORE INSERT ON SA."shoppers"
FOR EACH ROW
BEGIN
  SELECT shoppers_seq.nextval
  INTO :new.userid
  FROM dual;
END;
/


--
-- SHOPP_BI  (Trigger) 
--
--  Dependencies: 
--   SHOPPERS (Table)
--   STANDARD (Package)
--   SHOPP_SEQ (Sequence)
--   DUAL (Synonym)
--
CREATE OR REPLACE TRIGGER SA.shopp_bi BEFORE INSERT ON SA.SHOPPERS FOR EACH ROW
BEGIN SELECT shopp_seq.nextval INTO :new.userid FROM dual; END;
/


-- 
-- Non Foreign Key Constraints for Table SUBSCRIPTION 
-- 
ALTER TABLE SA.SUBSCRIPTION ADD (
  CONSTRAINT EMAIL_PK
  PRIMARY KEY
  (EMAIL)
  USING INDEX SA.EMAIL_PK
  ENABLE VALIDATE);


GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO EXP_FULL_DATABASE;

GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO IMP_FULL_DATABASE;
